env:
    name: Acrobot-v1
    max_episode_steps: 500
    obs_dim: 6
    act_dim: 3


agent:
    obs_dim: ${env.obs_dim}
    act_dim: ${env.act_dim}
    hidden_dim: 64
    optim:
        lr: 3e-4
        lam: 0.9
        gam: 0.99
        betas: [0.99, 0.999]
        eps: 1e-8
        replacing: True
        clip: 1.0
    from_pretrained: False
    weights_path: /Users/akshay/continual-learning/continual-learning/agent/weights/

algorithm:
    total_episodes: 1000
    episodes_per_update: 5